" setting

" 文字コードを UTF-8 に設定します
set fenc=utf-8
" 編集中のファイルが変更されたら自動で読み直します
set autoread
" 入力中のコマンドをステータスに表示します
set showcmd

" display
" 行番号を表示します
set number

" set cursorline

set smartindent

" タブ入力を空白に変換 
set expandtab

" タブを何文字の空白に変換するか 
set tabstop=4
" 自動インデント時に入力する空白の数 
set shiftwidth=4

" 検索した文字をハイライトする
set hls

" yank した文字列をクリップボードにコピー 
set clipboard=unnamed